Find file

diff --git a/buildspec-execute.yml b/buildspec-execute.yml
--- a/buildspec-execute.yml
+++ b/buildspec-execute.yml
@@ -4,7 +4,7 @@ env:
   variables:
     GITOPS_REPO: "alvarolinarescabre/huma-counter-href-10-sites"
     ARGOCD_PUSH_BRANCH: "main"
-    IMAGE_URI: "312910855403.dkr.ecr.eu-west-1.amazonaws.com/huma-counter-href-10-sites:latest"
+    K8S_BASE_IMAGE_NAME: "huma-app-image"
     ARGOCD_APP_NAME: "huma-counter-href-10-sites"
 
 phases:
@@ -20,9 +20,13 @@ phases:
       - echo "Obteniendo token de GitHub desde Secrets Manager..."
       - TOKEN_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:312910855403:secret:eks-argocd-app-deploy-github-token-OwVLLP --query SecretString --output text | jq -r '.github_token' || aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:312910855403:secret:eks-argocd-app-deploy-github-token-OwVLLP --query SecretString --output text)
 
-      - echo "Buscando imagedefinitions.json..."
-      - printf '[{"name":"%s","imageUri":"%s"}]' "$ARGOCD_APP_NAME" "$IMAGE_URI" > imagedefinitions.json
-      
+      - echo "Leyendo imagedefinitions.json inyectado por CodePipeline..."
+      - |
+        if [ ! -f "imagedefinitions.json" ]; then
+          echo "Error: imagedefinitions.json no fue inyectado por CodePipeline."
+          exit 1
+        fi
+
       - echo "Leyendo imagedefinitions.json..."
       - IMAGE_URI=$(jq -r '.[0].imageUri' imagedefinitions.json)
       - |
@@ -40,7 +44,7 @@ phases:
       - TARGET_DIR="infraestructure/k8s/base"
       - cd "$TARGET_DIR"
       - echo "Actualizando kustomization.yaml con la nueva imagen usando Kustomize..."
-      - kustomize edit set image "${IMAGE_NAME}=${IMAGE_URI}"
+      - kustomize edit set image ${K8S_BASE_IMAGE_NAME}=${IMAGE_NAME}:${IMAGE_TAG}
       - cat kustomization.yaml
       - ls -la
       
